### ISSUE TITLE
Support for VT-52 and other type of terminal and screen sizes.

### ISSUE THREAD

**Issue by MiguelVis** [udo-munk/s#3]
Hi Udo.

Is it planned to have support for other type of terminal and screen sizes, like VT-52, etc.?

For example, my real CP/M computer is an Amstrad PCW with a VT-52 like 32x90 screen and I was wondering if I could port S in a "standard way" having in mind other "official" ports or not.

The obvious path to achieve this is to modify the file screen.c in a compatible way, but maybe we could think in a configuration file or something like that.

Thanks.

**Comment by udo-munk** [comment]
Hi Miguel,
during the 80's we ported UNIX termcap to CP/M and using it for software that came from UNIX. Problem with this was that even a small termcap library needs ca. 5KB memory, which will reduce the edit buffer for s even more. So I would suggest to add VT52 and ADM3A terminals to screen.c with apropriate #ifdef's, then one can compile it with -DANSI, -DVT52 ... for the needed terminal.

**Comment by MiguelVis** [comment]
Hi Udo.

Ok, I will follow that path and pull a request asap.

Thanks.
