### ISSUE TITLE
It would be good if you could please be clear about the software's true license terms

### ISSUE THREAD

**Issue by unforgettableid** [udo-munk/s#4]
Hi!

I went to the [Miller Lab homepage](http://www.bx.psu.edu/miller_lab/), clicked "Other software", then clicked "software".  This got me a copy of Dr. Miller's official Software Tools Sampler tarball.  I looked inside; there was no license file.

I assume that, unless the copyright holder has stated otherwise, Dr. Miller's original `s` code is source-available freeware, but _not_ true open-source software.

(It's unclear to me whether the copyright holder is Dr. Miller or Prentice-Hall.  If you want to try contacting Dr. Miller, his various email addresses are listed [here](http://globin.bx.psu.edu/html/contact.html) and [here](https://bio.psu.edu/directory/wcm2).  Prentice-Hall is now owned by Pearson; their permissions-request system is [here](https://www.pearson.com/corporate/global-permission-granting.html).)

If I'm correct in guessing that Dr. Miller's original code is _not_ true open-source code, then is it possible you could please delete [your LICENSE file](https://github.com/udo-munk/s/blob/master/LICENSE) in order to avoid accidentally confusing anyone?

Thanks in advance!

**Comment by udo-munk** [comment]
Right, there is no license file included and the sources were made public available in book form and in machine readable file form. This is not 'my' LICENSE file, but the usual template provided here for such cases. If you are not happy with your guessing feel free to contact the author and try to get a license file you're happy with, and provide it here.

Thanks in advance.
